package discovery;

import java.awt.geom.*;

/*
 * LSystemApplet.java
 *
 * Created on August 31, 2004
 * Created by Joel Rathgaber
 */
public class LSystemApplet extends javax.swing.JApplet {

/*
 * The LSystemApplet class is simply a user interface that provides the
 * user a simple way to adjust different parameters of the bracketed
 * L-System and display the corresponding image.
 */
    
    public void init() {
        initComponents();
        displayPanel = new LSystemDisplayPanel();
        displayPanel.setPreferredSize(new java.awt.Dimension(512, 512));
        getContentPane().add(displayPanel, java.awt.BorderLayout.CENTER);
        displayPanel.setSize(512, 512);
    }
    
    /* This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        sidePanel = new javax.swing.JPanel();
        axiomLabel = new javax.swing.JLabel();
        axiomText = new javax.swing.JTextField();
        ruleLabel = new javax.swing.JLabel();
        ruleText = new javax.swing.JTextField();
        alphaLabel = new javax.swing.JLabel();
        alphaText = new javax.swing.JTextField();
        stemLabel = new javax.swing.JLabel();
        stemText = new javax.swing.JTextField();
        iterationLabel = new javax.swing.JLabel();
        iterationSpinner = new javax.swing.JSpinner();
        drawButton = new javax.swing.JButton();

        sidePanel.setLayout(new java.awt.GridLayout(5, 2));

        axiomLabel.setText("Axiom");
        sidePanel.add(axiomLabel);

        axiomText.setEditable(false);
        axiomText.setText("F");
        sidePanel.add(axiomText);

        ruleLabel.setText("Rule");
        sidePanel.add(ruleLabel);

        ruleText.setText("F[-F]F[+F][F]");
        sidePanel.add(ruleText);

        alphaLabel.setText("Alpha");
        sidePanel.add(alphaLabel);

        alphaText.setText("15");
        sidePanel.add(alphaText);

        stemLabel.setText("Stem Length");
        sidePanel.add(stemLabel);

        stemText.setText("10");
        sidePanel.add(stemText);

        iterationLabel.setText("Iterations");
        sidePanel.add(iterationLabel);

        sidePanel.add(iterationSpinner);

        getContentPane().add(sidePanel, java.awt.BorderLayout.EAST);

        drawButton.setText("Draw Plant!");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });

        getContentPane().add(drawButton, java.awt.BorderLayout.SOUTH);

    }
    // </editor-fold>//GEN-END:initComponents

    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButtonActionPerformed
        drawPlant();
    }//GEN-LAST:event_drawButtonActionPerformed
    
	/*
	 * Retrieves all the parameters from the applet's components and passes them
	 * to the display panel.
	 */
    private void drawPlant() {
        Integer iter = (Integer)iterationSpinner.getValue();
        String axiom = axiomText.getText();
        String rule = ruleText.getText();
        float alpha = Float.parseFloat(alphaText.getText());
        int stem = Integer.parseInt(stemText.getText());
        
        int midX = displayPanel.getWidth() / 2;
        
        Point2D.Float root = new Point2D.Float(midX, 0);
        LSystem plant = new LSystem(root, axiom, rule);
        plant.setAlphaDegrees(alpha);
        plant.setStemLength(stem);
        displayPanel.setPlant(plant.drawPlant(iter.intValue()));
        repaint();
    }
    
    private LSystemDisplayPanel displayPanel;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alphaLabel;
    private javax.swing.JTextField alphaText;
    private javax.swing.JLabel axiomLabel;
    private javax.swing.JTextField axiomText;
    private javax.swing.JButton drawButton;
    private javax.swing.JLabel iterationLabel;
    private javax.swing.JSpinner iterationSpinner;
    private javax.swing.JLabel ruleLabel;
    private javax.swing.JTextField ruleText;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel stemLabel;
    private javax.swing.JTextField stemText;
    // End of variables declaration//GEN-END:variables
    
}
